

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '695707885782-cr87jeea0489mtlesed0hku32enbdmqj'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '832KeFXQClb8Hrj3WvsTzV3s'

#SOCIAL_AUTH_TWITTER_KEY = 'w1OBaA7U4S2tpwLDFtlU2PzLd'
#SOCIAL_AUTH_TWITTER_SECRET = 'wHdEcutEbmFVr4cDKLa5ozKr0EvJzEOYUILUFiB1MmR6XvJmXp'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/chats/'
SOCIAL_AUTH_LOGIN_URL = '/'
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_EMAILS = ['mary.e.ellis@gmail.com', 'lisamlauck@gmail.com', 'roxila@gmail.com']
